services:
  migration.150512:
    class: Smartling\DbAl\Migrations\Migration150512

  migration.150619:
    class: Smartling\DbAl\Migrations\Migration150619

  migration.151222:
    class: Smartling\DbAl\Migrations\Migration151222

  migration.160125:
    class: Smartling\DbAl\Migrations\Migration160125

  migration.160223:
    class: Smartling\DbAl\Migrations\Migration160223

  migration.160411:
    class: Smartling\DbAl\Migrations\Migration160411

  migration.160413:
    class: Smartling\DbAl\Migrations\Migration160413

  migration.160414:
    class: Smartling\DbAl\Migrations\Migration160414

  migration.160603:
    class: Smartling\DbAl\Migrations\Migration160603

  migration.161010:
    class: Smartling\DbAl\Migrations\Migration161010

  migration.170412:
    class: Smartling\DbAl\Migrations\Migration170412

  migration.170421:
    class: Smartling\DbAl\Migrations\Migration170421

  migration.170517:
    class: Smartling\DbAl\Migrations\Migration170517

  migration.170620:
    class: Smartling\DbAl\Migrations\Migration170620

  migration.170922:
    class: Smartling\DbAl\Migrations\Migration170922

  migration.180208:
    class: Smartling\DbAl\Migrations\Migration180208

  migration.180515:
    class: Smartling\DbAl\Migrations\Migration180515

  migration.181002:
    class: Smartling\DbAl\Migrations\Migration181002

  migration.200528:
    class: Smartling\DbAl\Migrations\Migration200528

  migration.210406:
    class: Smartling\DbAl\Migrations\Migration210406

  migration.210825:
    class: Smartling\DbAl\Migrations\Migration210825

  manager.db.migrations:
    class: Smartling\DbAl\Migrations\DbMigrationManager
    calls:
      - [ "registerMigration", [ "@migration.150512" ]]
      - [ "registerMigration", [ "@migration.150619" ]]
      - [ "registerMigration", [ "@migration.151222" ]]
      - [ "registerMigration", [ "@migration.160125" ]]
      - [ "registerMigration", [ "@migration.160223" ]]
      - [ "registerMigration", [ "@migration.160411" ]]
      - [ "registerMigration", [ "@migration.160413" ]]
      - [ "registerMigration", [ "@migration.160414" ]]
      - [ "registerMigration", [ "@migration.160603" ]]
      - [ "registerMigration", [ "@migration.161010" ]]
      - [ "registerMigration", [ "@migration.170412" ]]
      - [ "registerMigration", [ "@migration.170421" ]]
      - [ "registerMigration", [ "@migration.170517" ]]
      - [ "registerMigration", [ "@migration.170620" ]]
      - [ "registerMigration", [ "@migration.170922" ]]
      - [ "registerMigration", [ "@migration.180208" ]]
      - [ "registerMigration", [ "@migration.180515" ]]
      - [ "registerMigration", [ "@migration.181002" ]]
      - [ "registerMigration", [ "@migration.200528" ]]
      - [ "registerMigration", [ "@migration.210406" ]]
      - [ "registerMigration", [ "@migration.210825" ]]
